/*
 * ufs_all_test — end-to-end validation of the user-space filesystem host
 * (ufsd) across all backends.
 *
 * QEMU layout (DEV_CLASS_BLOCK indices):
 *   0  bus.0 primary storage fat32.img (used for kernel boot)
 *   1  bus.2 fat scratch (existing UFS_SCRATCH_IMG, contains HELLO.TXT)
 *   2  bus.4 ext4 scratch (mke2fs -d preseeded with hello.txt)
 *   3  bus.6 iso9660 (generated by mkisofs_test, contains HELLO.TXT and
 *      SUB/NESTED.TXT)
 *   4  bus.7 ntfs scratch (quick-formatted with mkntfs, empty volume)
 *
 * Each backend brings up its own ufsd instance and runs a POSIX operation
 * sequence:
 *   fat : read back / write then read back / list directory / delete
 *   ext4: read back preseeded content / create-write-read / rename / delete
 *   iso : verify read-only content / list directory / read nested path
 *   ntfs: mount parse / create-write-read-back / directory ops / SIGKILL
 *         restart persistence / delete
 */
#define _GNU_SOURCE
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <unistd.h>
#include <fcntl.h>
#include <sys/stat.h>
#include <dirent.h>
#include <errno.h>
#include <signal.h>
#include <sys/wait.h>
#include <sys/mount.h>

static int fail(const char *tag, const char *why)
{
    printf("%s: FAIL %s\n", tag, why);
    return 1;
}

static pid_t spawn_ufsd(const char *mp, const char *idx, const char *fstype)
{
    pid_t pid = fork();
    if (pid == 0) {
        execl("/bin/ufsd-rv", "ufsd-rv", mp, idx, fstype, (char *)0);
        _exit(90);
    }
    return pid;
}

/* Shared crash-recovery sequence: SIGKILL the instance -> reap -> unmount
 * (the kernel-side mount still points at the dead channel, so it must be
 * unmounted before it can be re-registered) -> bring it back up. */
static int kill_and_remount_ufsd(pid_t victim, const char *mp,
                                 const char *idx, const char *fstype)
{
    kill(victim, SIGKILL);
    waitpid(victim, NULL, 0);
    if (umount2(mp, 0) != 0)
        return -1;
    spawn_ufsd(mp, idx, fstype);
    return 0;
}

static int wait_path(const char *path, int tries)
{
    struct stat st;
    for (int i = 0; i < tries; i++) {
        if (stat(path, &st) == 0)
            return 0;
        usleep(20000);
    }
    return -1;
}

static int read_all(const char *path, char *buf, size_t cap)
{
    int fd = open(path, O_RDONLY);
    if (fd < 0)
        return -1;
    ssize_t n = read(fd, buf, cap - 1);
    close(fd);
    if (n < 0)
        return -1;
    buf[n] = '\0';
    return (int)n;
}

static unsigned char pattern[8192];

static int roundtrip(const char *tag, const char *dir, const char *name)
{
    char path[256];
    snprintf(path, sizeof(path), "%s/%s", dir, name);

    for (size_t i = 0; i < sizeof(pattern); i++)
        pattern[i] = (unsigned char)(i * 31 + 7);

    int fd = open(path, O_CREAT | O_TRUNC | O_WRONLY, 0644);
    if (fd < 0) {
        printf("%s: create errno=%d (%s)\n", tag, errno, path);
        return fail(tag, "create");
    }
    ssize_t wn = write(fd, pattern, sizeof(pattern));
    if (wn != (ssize_t)sizeof(pattern))
        printf("%s: write ret=%zd errno=%d\n", tag, wn, errno);
    close(fd);
    if (wn != (ssize_t)sizeof(pattern))
        return fail(tag, "write size");

    static unsigned char back[8192];
    fd = open(path, O_RDONLY);
    if (fd < 0) {
        printf("%s: reopen errno=%d\n", tag, errno);
        return fail(tag, "reopen");
    }
    ssize_t rn = read(fd, back, sizeof(back));
    close(fd);
    if (rn != (ssize_t)sizeof(pattern)) {
        printf("%s: read ret=%zd errno=%d\n", tag, rn, errno);
        return fail(tag, "read size");
    }
    for (size_t i = 0; i < sizeof(pattern); i++) {
        if (pattern[i] != back[i]) {
            printf("%s: first diff at %zu want=%02x got=%02x\n",
                   tag, i, pattern[i], back[i]);
            break;
        }
    }
    if (memcmp(pattern, back, sizeof(pattern)) != 0)
        return fail(tag, "read-back mismatch");
    return 0;
}

static int test_fat(void)
{
    const char *tag = "UXFS_FAT";
    struct stat st0;
    if (stat("/ufs/HELLO.TXT", &st0) != 0)
        spawn_ufsd("/ufs", "1", "fat"); /* fallback self-start when
                            * svcmgr is not
                            * supervising */
    if (wait_path("/ufs/HELLO.TXT", 500))
        return fail(tag, "/ufs not visible");

    char buf[64];
    if (read_all("/ufs/HELLO.TXT", buf, sizeof(buf)) <= 0 ||
        strcmp(buf, "hello-uxfs\n") != 0)
        return fail(tag, "content mismatch");

    if (roundtrip(tag, "/ufs", "ROUND.BIN"))
        return 1;
    if (unlink("/ufs/ROUND.BIN") != 0)
        return fail(tag, "unlink");

    printf("%s: PASS\n", tag);
    return 0;
}

static int test_ext4(void)
{
    const char *tag = "UXFS_EXT4";
    spawn_ufsd("/uext4", "2", "ext4");
    if (wait_path("/uext4/hello.txt", 500))
        return fail(tag, "/uext4 not visible");

    char buf[64];
    if (read_all("/uext4/hello.txt", buf, sizeof(buf)) <= 0 ||
        strcmp(buf, "hello ext4 user-space\n") != 0)
        return fail(tag, "seeded content mismatch");

    if (roundtrip(tag, "/uext4", "EXT4BIN.BIN"))
        return 1;

    /* rename semantics (ext4 supports the full rename primitive) */
    if (rename("/uext4/EXT4BIN.BIN", "/uext4/RENAMED.BIN") != 0)
        return fail(tag, "rename");
    struct stat st;
    if (stat("/uext4/EXT4BIN.BIN", &st) == 0 || stat("/uext4/RENAMED.BIN", &st) != 0)
        return fail(tag, "rename effect");

    if (unlink("/uext4/RENAMED.BIN") != 0)
        return fail(tag, "unlink");

    printf("%s: PASS\n", tag);
    return 0;
}

static int test_iso(void)
{
    const char *tag = "UXFS_ISO";
    spawn_ufsd("/uiso", "3", "iso9660");
    if (wait_path("/uiso/hello.txt", 500))
        return fail(tag, "/uiso not visible");

    char buf[64];
    if (read_all("/uiso/hello.txt", buf, sizeof(buf)) <= 0 ||
        strcmp(buf, "hello iso9660 world\n") != 0)
        return fail(tag, "HELLO.TXT content");

    if (read_all("/uiso/sub/nested.txt", buf, sizeof(buf)) <= 0 ||
        strcmp(buf, "nested file content\n") != 0)
        return fail(tag, "NESTED.TXT content");

    DIR *d = opendir("/uiso");
    if (!d)
        return fail(tag, "opendir");
    int saw_sub = 0;
    struct dirent *ent;
    while ((ent = readdir(d)) != NULL)
        if (strcmp(ent->d_name, "sub") == 0)
            saw_sub = 1;
    closedir(d);
    if (!saw_sub)
        return fail(tag, "readdir missing SUB");

    printf("%s: PASS\n", tag);
    return 0;
}

/* The ntfs backend has opened read-write: verify mount/MFT parsing,
 * create-write-read-back, directory operations, deletion, and data
 * persistence across a SIGKILL restart (an in-tree end-to-end test of the
 * kernel ntfs write path). */
static int test_ntfs(void)
{
    const char *tag = "UXFS_NTFS";
    const char *mrk = "/untfs/RESTART.MRK";

    pid_t a = spawn_ufsd("/untfs", "4", "ntfs");
    if (wait_path("/untfs", 500))
        return fail(tag, "/untfs not visible");

    struct stat st;
    if (stat("/untfs", &st) != 0)
        return fail(tag, "stat /untfs failed");
    if (!S_ISDIR(st.st_mode)) {
        printf("UXFS_NTFS: dbg mode=%o size=%zu\n", st.st_mode,
               (size_t)st.st_size);
        return fail(tag, "root not a directory");
    }

    /* Create-write-read-back: an 8KB pseudorandom pattern covers
     * non-resident data streams and cluster allocation */
    if (roundtrip(tag, "/untfs", "NTFSBIN.BIN"))
        return 1;

    /* Directory ops: mkdir -> nested create and read -> delete the file
     * before rmdir */
    if (mkdir("/untfs/sub", 0755) != 0)
        return fail(tag, "mkdir");
    char npath[256];
    snprintf(npath, sizeof(npath), "%s/%s", "/untfs/sub", "NESTED.TXT");
    int fd = open(npath, O_CREAT | O_WRONLY, 0644);
    if (fd < 0)
        return fail(tag, "nested create");
    if (write(fd, "ntfs nested\n", 12) != 12) {
        close(fd);
        return fail(tag, "nested write");
    }
    close(fd);

    /* Persistence marker: must survive a restart across instances */
    fd = open(mrk, O_CREAT | O_WRONLY, 0644);
    if (fd < 0)
        return fail(tag, "create marker");
    if (write(fd, "survive-restart\n", 16) != 16) {
        close(fd);
        return fail(tag, "marker write");
    }
    close(fd);

    DIR *d = opendir("/untfs");
    if (!d)
        return fail(tag, "opendir");
    int saw_bin = 0, saw_sub = 0;
    struct dirent *ent;
    while ((ent = readdir(d)) != NULL) {
        if (strcmp(ent->d_name, "NTFSBIN.BIN") == 0)
            saw_bin = 1;
        if (strcmp(ent->d_name, "sub") == 0)
            saw_sub = 1;
    }
    closedir(d);
    if (!saw_bin || !saw_sub)
        return fail(tag, "readdir missing created entries");

    /* Crash-recovery drill: SIGKILL the instance -> unmount -> restart ->
     * data still there */
    if (kill_and_remount_ufsd(a, "/untfs", "4", "ntfs") != 0)
        return fail(tag, "remount after crash");
    if (wait_path(mrk, 500))
        return fail(tag, "instance B not visible");

    char buf[32];
    memset(buf, 0, sizeof(buf));
    if (read_all(mrk, buf, sizeof(buf)) != 16 ||
        strcmp(buf, "survive-restart\n") != 0)
        return fail(tag, "marker content lost across restart");

    memset(buf, 0, sizeof(buf));
    if (read_all(npath, buf, sizeof(buf)) != 12 ||
        strcmp(buf, "ntfs nested\n") != 0)
        return fail(tag, "nested content lost across restart");

    /* Cleanup: deleting the path reclaims both the clusters and the MFT
     * record */
    if (unlink("/untfs/NTFSBIN.BIN") != 0)
        return fail(tag, "unlink");
    if (unlink(npath) != 0)
        return fail(tag, "nested unlink");
    if (rmdir("/untfs/sub") != 0)
        return fail(tag, "rmdir");
    unlink(mrk);

    printf("%s: PASS\n", tag);
    return 0;
}

/* Crash-recovery drill: on the separate mount point /ufs2, verify the full
 * "kill the instance -> unmount -> restart -> data persists" contract (a
 * measured test of the recovery semantics in 06-user-fs.md). */
static int test_restart(void)
{
    const char *tag = "UXFS_RESTART";
    const char *mrk = "/ufs2/RESTART.MRK";

    pid_t a = spawn_ufsd("/ufs2", "1", "fat");
    if (wait_path(mrk ? "/ufs2" : mrk, 500))
        return fail(tag, "/ufs2 first instance not visible");

    int fd = open(mrk, O_CREAT | O_WRONLY, 0644);
    if (fd < 0)
        return fail(tag, "create marker");
    if (write(fd, "survive-restart\n", 16) != 16) {
        close(fd);
        return fail(tag, "marker write");
    }
    close(fd);

    if (kill_and_remount_ufsd(a, "/ufs2", "1", "fat") != 0)
        return fail(tag, "umount after crash");
    if (wait_path(mrk, 500))
        return fail(tag, "instance B not visible");

    char buf[32];
    memset(buf, 0, sizeof(buf));
    int fd2 = open(mrk, O_RDONLY);
    if (fd2 < 0)
        return fail(tag, "marker reopen");
    ssize_t n = read(fd2, buf, sizeof(buf) - 1);
    close(fd2);
    if (n != 16 || strcmp(buf, "survive-restart\n") != 0)
        return fail(tag, "marker content lost across restart");

    unlink(mrk);
    printf("%s: PASS\n", tag);
    return 0;
}

int main(void)
{
    if (test_fat())
        return 1;
    if (test_ext4())
        return 1;
    if (test_iso())
        return 1;
    if (test_ntfs())
        return 1;
    if (test_restart())
        return 1;
    printf("UXFS_ALL: PASS\n");
    return 0;
}
