// AOSCC 2026 presentation theme for Touying 0.7.4.
// Visual source: aoscc-2026-template.pptx and background.svg in this folder.
// Generated by GPT-5.6 Sol High

#import "@preview/touying:0.7.4": *
#import "@preview/pointless-size:0.1.2": zh, zihao

#let aoscc-green = rgb("#5b6052")
#let aoscc-ink = rgb("#363636")
#let aoscc-paper = rgb("#f3f4f0")

#let _type = (
  display: zh(0),
  subtitle: zh(1),
  author: zh(2),
  body: zh(-1),
  attribution: zh(-2),
)

#let _page-width = 841.89pt
#let _page-height = 473.56pt
#let _left = 65.8pt
#let _rule-left = 47.3pt
#let _content-margin = 47.3pt
#let _top = 47.4pt
#let _brand-background = image(
  "background.svg",
  width: 100%,
  height: 100%,
  fit: "stretch",
)

#let _title-rule(height: 52pt) = rect(
  width: 5.3pt,
  height: height,
  fill: aoscc-green,
  stroke: none,
)

#let _slide-heading(self) = {
  let headings = self.at("headings", default: ())
  if headings.len() > 0 {
    text(
      font: ("Open Sans", "Noto Sans CJK SC"),
      size: _type.display,
      weight: 450,
      fill: aoscc-ink,
      headings.last().body,
    )
  }
}

#let _normal-layout(self, body) = block(
  width: _page-width,
  height: _page-height,
  above: 0pt,
  below: 0pt,
  breakable: false,
  [
    #place(
      top + left,
      dx: _rule-left,
      dy: _top,
      _title-rule(),
    )
    #place(
      top + left,
      dx: _left,
      dy: _top + 6pt,
      block(
        width: 63%,
        _slide-heading(self),
      ),
    )
    #pad(
      left: _content-margin,
      right: _content-margin,
      top: 118.5pt,
      bottom: 39pt,
      body,
    )
  ],
)

/// Show each body on a separate subslide while keeping one shared `==` title
/// and one logical slide number. Example: `#subslides[First][Second]`.
#let subslides(
  position: top + left,
  stretch: true,
  ..bodies,
) = alternatives(
  position: position,
  stretch: stretch,
  ..bodies,
)

/// Standard content slide. Heading-driven `==` slides use this automatically.
#let slide(
  config: (:),
  repeat: auto,
  setting: body => body,
  composer: auto,
  ..bodies,
) = touying-slide-wrapper(self => {
  touying-slide(
    self: self,
    config: config,
    repeat: repeat,
    composer: composer,
    setting: body => _normal-layout(self, setting(body)),
    ..bodies,
  )
})

/// Cover slide using `title`, `subtitle`, `author`, and `section` from `aoscc-theme`.
#let title-slide(config: (:)) = touying-slide-wrapper(self => {
  let self = utils.merge-dicts(
    self,
    config-common(freeze-slide-counter: true),
    config,
  )
  touying-slide(
    self: self,
    repeat: 1,
    setting: body => block(
      width: _page-width,
      height: _page-height,
      above: 0pt,
      below: 0pt,
      breakable: false,
      [
        #place(
          top + left,
          dx: _rule-left,
          dy: _top,
          _title-rule(height: 52pt),
        )
        #place(
          top + left,
          dx: _left,
          dy: 82.7pt,
          text(
            size: _type.subtitle,
            weight: 450,
            fill: aoscc-green,
            self.info.extra.at("section", default: [AOSCC 2026 | 欢迎]),
          ),
        )
        #place(
          top + left,
          dx: _left,
          dy: 142pt,
          text(size: _type.subtitle, weight: 450, self.info.subtitle),
        )
        #place(
          top + left,
          dx: _left,
          dy: 191.5pt,
          line(length: 75%, stroke: .7pt + rgb("#bbc2b0")),
        )
        #place(
          top + left,
          dx: _left,
          dy: 211pt,
          block(
            width: 75%,
            text(size: _type.display, weight: 450, self.info.title),
          ),
        )
        #place(
          top + left,
          dx: _left,
          dy: 331pt,
          text(size: _type.author, weight: 450, self.info.author),
        )
        #body
      ],
    ),
  )
})

/// Full-slide section divider. With no body, it uses the current level-one heading.
#let section-slide(config: (:), body) = touying-slide-wrapper(self => {
  let self = utils.merge-dicts(self, config, config-common(freeze-slide-counter: true))
  let section-title = if body == none {
    utils.display-current-heading(level: 1, depth: 1)
  } else {
    body
  }
  touying-slide(
    self: self,
    repeat: 1,
    setting: content => block(
      width: _page-width,
      height: _page-height,
      above: 0pt,
      below: 0pt,
      breakable: false,
      [
        #place(top + left, dx: _rule-left, dy: _top, _title-rule(height: 72pt))
        #place(
          left + horizon,
          dx: 100pt,
          block(
            width: 60%,
            text(size: _type.display, weight: 450, fill: aoscc-ink, section-title),
          ),
        )
        #content
      ],
    ),
  )
})

/// Emphasis/quotation slide derived from the source deck's “仅标题” layout.
#let quote-slide(config: (:), attribution: none, body) = touying-slide-wrapper(self => {
  let self = utils.merge-dicts(self, config)
  touying-slide(
    self: self,
    repeat: 1,
    setting: content => block(
      width: _page-width,
      height: _page-height,
      above: 0pt,
      below: 0pt,
      breakable: false,
      [
        #place(top + left, dx: _rule-left, dy: _top, _title-rule(height: 52pt))
        #place(
          top + left,
          dx: 54pt,
          dy: 48pt,
          scale(170%, text(size: _type.display, weight: 700, fill: aoscc-green)[“]),
        )
        #place(
          left + horizon,
          dx: 100pt,
          block(
            width: 42%,
            text(size: _type.display, weight: 450, fill: aoscc-ink, body),
          ),
        )
        #place(
          top + left,
          dx: 438pt,
          dy: 301pt,
          scale(170%, text(size: _type.display, weight: 700, fill: aoscc-green)[”]),
        )
        #if attribution != none {
          place(
            top + left,
            dx: 100pt,
            dy: 292pt,
            text(size: _type.attribution, fill: aoscc-green, attribution),
          )
        }
        #content
      ],
    ),
  )
})

/// Install the AOSCC 2026 theme and presentation metadata.
#let aoscc-theme(
  title: none,
  subtitle: none,
  author: none,
  date: none,
  section: [AOSCC 2026 | 欢迎],
  ..args,
  body,
) = {
  show: zihao(-1)
  set text(
    lang: "zh",
    font: ("Open Sans", "Noto Sans CJK SC"),
    weight: 400,
    fill: aoscc-ink,
  )
  set par(leading: .45em)
  set list(indent: 1.15em, body-indent: .55em, spacing: .55em)

  show: touying-slides.with(
    config-page(
      width: _page-width,
      height: _page-height,
      margin: 0pt,
      fill: aoscc-paper,
      background: _brand-background,
    ),
    config-common(
      slide-level: 2,
      slide-fn: slide,
      new-section-slide-fn: section-slide,
      receive-body-for-new-section-slide-fn: false,
      breakable: false,
      clip: false,
      detect-overflow: true,
      zero-margin-header: false,
      zero-margin-footer: false,
    ),
    config-info(
      title: title,
      subtitle: subtitle,
      author: author,
      date: date,
      extra: (section: section),
    ),
    config-colors(
      primary: aoscc-green,
      neutral: aoscc-green,
      neutral-lightest: aoscc-paper,
      neutral-darkest: aoscc-ink,
    ),
    ..args,
  )

  body
}
