Section "Device"
    Identifier  "A20OS GPU"
    Driver      "fbdev"
    Option      "ShadowFB" "true"
EndSection

Section "ServerFlags"
    Option "DontVTSwitch" "true"
    Option "AllowMouseOpenFail" "true"
EndSection
