/* Generated by tools/a20idl.py; do not edit by hand. */
#ifndef _A20_SERVICES_IDL_H
#define _A20_SERVICES_IDL_H

#define A20_SERVICES_IDL_VERSION 1u
#define A20_SVC_CRASH_CODE (42)
#define RTCD_REQ_TIME (0x54)
#define RTCD_REQ_ALARM (0x41)
#define RTCD_REQ_CRASH (0x43)
#define UBD_REQ_READ (0x52)
#define UBD_REQ_WRITE (0x57)
#define UBD_REQ_CRASH (0x43)

#endif
