#!/usr/bin/env python3
"""Generate a small, deterministic C constant header from A20 service IDL.

The initial IDL deliberately covers constants only. Message layout and
typed binding generation are the next extension; keeping the first grammar
small makes protocol versioning and generated-source checks usable now.
"""
import argparse
import re
from pathlib import Path


CONST = re.compile(r"^\s*const\s+([A-Za-z_][A-Za-z0-9_]*)\s*=\s*([^;]+);\s*$")
VERSION = re.compile(r"^\s*interface\s+[A-Za-z_][A-Za-z0-9_]*\s+version\s+(\d+)\s*\{")


def generate(source: Path) -> str:
    version = None
    constants = []
    for line in source.read_text(encoding="ascii").splitlines():
        if line.lstrip().startswith("//") or not line.strip():
            continue
        if version is None:
            match = VERSION.match(line)
            if match:
                version = int(match.group(1))
                continue
        match = CONST.match(line)
        if match:
            constants.append((match.group(1), match.group(2).strip()))
    if version is None:
        raise SystemExit(f"{source}: missing interface version")
    if len({name for name, _ in constants}) != len(constants):
        raise SystemExit(f"{source}: duplicate constant")
    lines = [
        "/* Generated by tools/a20idl.py; do not edit by hand. */",
        "#ifndef _A20_SERVICES_IDL_H",
        "#define _A20_SERVICES_IDL_H",
        "",
        f"#define A20_SERVICES_IDL_VERSION {version}u",
    ]
    lines.extend(f"#define {name} ({value})" for name, value in constants)
    lines.extend(["", "#endif", ""])
    return "\n".join(lines)


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("source", type=Path)
    parser.add_argument("output", type=Path)
    args = parser.parse_args()
    args.output.write_text(generate(args.source), encoding="ascii")


if __name__ == "__main__":
    main()
