#!/usr/bin/env python3
"""Generate a compact kernel symbol table (kallsyms) for oops backtraces.

Reads the linked kernel ELF directly (pure stdlib, no nm required) and emits
a C source defining:

  static const char  kallsyms_names[];
  static const uint64_t kallsyms_addrs[];
  static const uint32_t kallsyms_name_offs[];
  #define KALLSYMS_COUNT <n>

The addrs array is ascending so the kernel can binary-search it.  Only
symbols inside the executable LOAD segment are kept, so the table is small
(one entry per function/global of the kernel image).

Usage: gen_kallsyms.py <kernel.elf> <output.c>
"""

import struct
import sys

ELF_CLASS_64 = 2
EM_AARCH64 = 183
EM_RISCV = 243
EM_X86_64 = 62
EM_LOONGARCH = 258
EM_ARM = 40
EM_PPC64 = 21

SUPPORTED_TEXT_TYPES = frozenset(
    ["T", "t", "W", "w", "D", "d", "R", "r", "B", "b", "A", "a", "i"]
)


def parse_elf(path):
    with open(path, "rb") as f:
        data = f.read()
    if data[:4] != b"\x7fELF":
        raise SystemExit(f"{path}: not an ELF file")

    ei_class = data[4]
    if ei_class == ELF_CLASS_64:
        ehdr = struct.unpack_from("<16sHHIQQQIHHHHHH", data, 0)
        e_shoff, e_shentsize, e_shnum, e_shstrndx = ehdr[6], ehdr[11], ehdr[12], ehdr[13]
        sh_fmt = "<IIQQQQIIQQ"
        sh_size = 64
    else:
        ehdr = struct.unpack_from("<16sHHIIIIIHHHHHH", data, 0)
        e_shoff, e_shentsize, e_shnum, e_shstrndx = ehdr[6], ehdr[11], ehdr[12], ehdr[13]
        sh_fmt = "<IIIIIIIIII"
        sh_size = 40

    sections = []
    for i in range(e_shnum):
        off = e_shoff + i * sh_size
        sh = struct.unpack_from(sh_fmt, data, off)
        if ei_class == ELF_CLASS_64:
            sh_name, sh_type, sh_flags, sh_addr, sh_offset, sh_size_, _, _, sh_link, _ = sh
        else:
            sh_name, sh_type, sh_flags, sh_addr, sh_offset, sh_size_, sh_link, _, _, _ = sh
        sections.append((sh_name, sh_type, sh_addr, sh_offset, sh_size_, sh_link))

    if not sections:
        return [], []

    shstr = sections[e_shstrndx]
    shstr_data = data[shstr[3]:shstr[3] + shstr[4]]
    sec_names = {}
    for i, s in enumerate(sections):
        name_off = s[0]
        end = shstr_data.find(b"\0", name_off)
        sec_names[i] = shstr_data[name_off:end].decode("latin1")

    symtab = None
    strtab = None
    text_ranges = []
    for i, s in enumerate(sections):
        name = sec_names[i]
        if name == ".symtab":
            symtab = s
        elif name == ".strtab":
            strtab = s
        elif name == ".text" and s[2] != 0:
            text_ranges.append((s[2], s[2] + s[4]))

    if not symtab or not strtab:
        return [], text_ranges

    str_data = data[strtab[3]:strtab[3] + strtab[4]]
    sym_fmt = "<IBBHQQ" if ei_class == ELF_CLASS_64 else "<IIIBBH"
    sym_size = 24 if ei_class == ELF_CLASS_64 else 16
    nsyms = symtab[4] // sym_size
    syms = []
    for i in range(nsyms):
        raw = struct.unpack_from(sym_fmt, data, symtab[3] + i * sym_size)
        if ei_class == ELF_CLASS_64:
            st_name, st_info, st_other, st_shndx, st_value, st_size = raw
        else:
            st_name, st_value, st_size, st_info, st_other, st_shndx = raw
        bind = st_info >> 4
        typ = st_info & 0xF
        if st_name >= len(str_data):
            continue
        name_end = str_data.find(b"\0", st_name)
        if name_end < 0:
            continue
        name = str_data[st_name:name_end]
        if typ == 2:  # STT_FUNC
            typ_char = "T" if bind == 1 else "t"
            syms.append((st_value, typ_char, name, st_size))
        elif typ == 1 and bind == 1 and st_value != 0:  # global STT_OBJECT
            syms.append((st_value, "D", name, st_size))

    return syms, text_ranges


def main():
    if len(sys.argv) != 3:
        print("usage: gen_kallsyms.py <kernel.elf> <output.c>", file=sys.stderr)
        return 2
    elf_path, out_path = sys.argv[1], sys.argv[2]

    syms, text_ranges = parse_elf(elf_path)
    if text_ranges:
        lo = min(r[0] for r in text_ranges)
        hi = max(r[1] for r in text_ranges)
        syms = [s for s in syms if lo <= s[0] < hi]
    else:
        syms = [s for s in syms if s[1] in ("T", "t", "W", "w")]

    syms.sort(key=lambda s: s[0])
    names = b"".join(s[2] + b"\0" for s in syms) if syms else b""
    count = len(syms)

    with open(out_path, "w") as f:
        f.write("/* Generated by tools/gen_kallsyms.py -- do not edit. */\n")
        f.write("#define KALLSYMS_COUNT %d\n" % count)
        f.write('#include "core/kallsyms.h"\n\n')
        if not syms:
            f.write("/* No symbols: kernel falls back to raw addresses. */\n")
            return 0
        f.write("static const char kallsyms_names[] = {\n")
        for i in range(0, len(names), 16):
            f.write("    ")
            f.write(", ".join(str(b) for b in names[i:i + 16]))
            f.write(",\n")
        f.write("};\n\n")
        f.write("static const uint64_t kallsyms_addrs[KALLSYMS_COUNT] = {\n")
        for i in range(0, len(syms), 4):
            f.write("    ")
            f.write(", ".join("0x%xULL" % (s[0],) for s in syms[i:i + 4]))
            f.write(",\n")
        f.write("};\n\n")
        f.write("static const uint32_t kallsyms_name_offs[KALLSYMS_COUNT] = {\n")
        off = 0
        offs = []
        for s in syms:
            offs.append(off)
            off += len(s[2]) + 1
        for i in range(0, len(offs), 8):
            f.write("    ")
            f.write(", ".join(str(o) for o in offs[i:i + 8]))
            f.write(",\n")
        f.write("};\n\n")
        f.write("const char *kallsyms_lookup(uint64_t addr, uint64_t *offset_out)\n")
        f.write("{\n")
        f.write("    int lo = 0, hi = KALLSYMS_COUNT - 1;\n")
        f.write("    while (lo <= hi) {\n")
        f.write("        int mid = (lo + hi) >> 1;\n")
        f.write("        if (kallsyms_addrs[mid] <= addr) {\n")
        f.write("            if ((unsigned)mid == KALLSYMS_COUNT - 1 ||\n")
        f.write("                kallsyms_addrs[mid + 1] > addr) {\n")
        f.write("                const char *name = &kallsyms_names[kallsyms_name_offs[mid]];\n")
        f.write("                if (offset_out)\n")
        f.write("                    *offset_out = addr - kallsyms_addrs[mid];\n")
        f.write("                return name;\n")
        f.write("            }\n")
        f.write("            lo = mid + 1;\n")
        f.write("        } else {\n")
        f.write("            hi = mid - 1;\n")
        f.write("        }\n")
        f.write("    }\n")
        f.write("    if (offset_out)\n")
        f.write("        *offset_out = addr;\n")
        f.write("    return NULL;\n")
        f.write("}\n\n")
        f.write("uint32_t kallsyms_count(void) { return KALLSYMS_COUNT; }\n")
    return 0


if __name__ == "__main__":
    sys.exit(main())
